### ISSUE TITLE
Duplicate Items on item lookup cause auction creation to fail

### ISSUE THREAD

**Issue by paroxysmal** [SterlingNerd/DiscordDkpBot#2]

**Comment by paroxysmal** [comment]
probably need some regex somewhere to denote the end of the line

.dkp startbid "Reaver" as an example you only want Reaver so you have to exclude all other search results and on top of that you need to have it create the auction if it still can't determine item lookup rather than failing due to item lookup issue.

**Comment by SterlingNerd** [comment]
Fixed
