### ISSUE TITLE
bot accepts bid of 2 items with 2 or 2x but not x2

### ISSUE THREAD

**Issue by paroxysmal** [SterlingNerd/DiscordDkpBot#7]

**Comment by SterlingNerd** [comment]
```startbids x2 "item"```

Doesn't really makes sense to me.

```startbids "item" x2``` makes a bit more sense, but with the optional duration parameter, it can get confusing. Also, the regex to support this REALLY sucks. \#notworth

**Comment by paroxysmal** [comment]
may not make sense but ive seen people trying to create an auction having it fail because they didn't get the # of items correct because they failed on the format
